apiVersion: v1
kind: Service
metadata:
  name: peer0-netflix-myapp
spec:
  ports:
    - name: peer0-netflix-myapp
      port: 7051
    - name: chaincode-listen
      port: 7052
  selector:
    run: peer0-netflix-myapp
